version: "2"
checks:
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 80
exclude_patterns:
  - "api/node_modules/"
  - "api/keys/"
  - "api/logs/"
  - "api/dist/"
  - "web/node_modules/"
  - "web/.cache/"
  - "web/public/"
  - "web/tailwind.config.js"