version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build:
    working_directory: ~/project
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/web
          cache-path: node_modules
          pkg-manager: yarn

  test:
    docker:
      - image: cimg/node:current
    steps:
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
