version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  install:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - run:
          name: Change directory
          command: cd web
      - node/install-yarn
      - run:
          name: Install Dependencies
          command: yarn install
      

  test:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - run:
          name: Change directory
          command: cd web
      - run: ls
      - run:
          name: Test
          command: yarn test

  deploy:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - run:
          name: Deploy SSH
          command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./matievisthekat.dev/deploy.sh”

workflows:
  version: 2
  ci:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
