version: 2.1
orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    working_directory: ~/web
    executor: node/default
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages:
          app-dir: ~/web
          cache-path: node_modules
          override-ci-command: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
