version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build:
    # working_directory: ./web
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - run:
          name: Change directory
          command: cd web
      - node/install-yarn
      - run:
          name: Install Dependencies
          command: yarn install
      

  test:
    # working_directory: ./web
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      # - checkout
      # - run:
      #     name: Change directory
      #     command: cd web
      # - node/install-yarn
      - run:
          name: Test
          command: yarn test

  deploy:
    docker:
    # specify the version you desire here (you might not want node)
    - image: circleci/node:7.10
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./matievisthekat.dev/deploy.sh”

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
