version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build:
    working_directory: ./web
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: List
          command: ls

  test:
    working_directory: ./web
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Test
          command: yarn test

  deploy-prod:
    docker:
    # specify the version you desire here (you might not want node)
    - image: circleci/node:7.10
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “./matievisthekat.dev/deploy.sh”

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
