
name: Build html

on:
  pull_request:
    types: [closed]
    branches: [gh-pages]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2
        if: github.event.pull_request.merged
        with:
          ref: gh-pages

      - name: Replace link to prod css
        run: for f in $(find ./ -name '*.html'); do sed -i 's/css\/raw/css\/prod/' $f; done

      - name: Commit
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'Github Actions'
          git pull --commit
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m '[pages] build html'
          
