name: Build css

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'css/raw/**/*.css'
      - 'sass/**/*.scss'
      - 'sass/**/*.sass'

jobs:
  sass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
          yarn: true

      - name: Install dependencies
        run: yarn

      - name: Compile Sass
        run: yarn sass

      - name: Commit updated css
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'Github Actions'
          git pull --commit
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m '[sass] build css'
      
      - name: Push origin master
        run: git push origin master

  postcss:
    needs: sass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install postcss & plugins
        run: yarn

      - name: Parse css
        run: yarn postcss

      - name: Commit updated css
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'Github Actions'
          git pull
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m '[postcss] parse css'
      
      - name: Push origin master
        run: git push origin master
