name: Build sass

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'sass/*'

jobs:
  sass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install Sass
        run: npm install -g sass

      - name: Verify Sass version
        run: sass --version

      - name: Compile Sass
        run: ./sass.sh

      - name: Commit updated css
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'Github Actions'
          git pull
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m '[sass] build css'
      
      - name: Push origin master
        run: git push origin master

  postcss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install postcss & plugins
        run: npm i -g postcss postcss-cli autoprefixer cssnano postcss-preset-env postcss-reporter

      - name: Verify postcss version
        run: postcss --version

      - name: Parse css
        run: ./postcss.sh

      - name: Commit updated css
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'Github Actions'
          git pull
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m '[postcss] parse css'
      
      - name: Push origin master
        run: git push origin master
