name: Build js

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ts/**/*.ts

jobs:
  build_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
          yarn: true

      - name: Install dependencies
        run: yarn

      - name: Compile TypeScript
        run: yarn tsc

      - name: Commit updated js
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'Github Actions'
          git pull --commit
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m '[typescript] build js'

      - name: Push origin master
        run: git push origin master
