name: Deploy

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: cd web && yarn

      - name: Clean web directory
        run: cd web && yarn clean

      - name: Build website
        run: cd web && yarn build
        env:
          API: https://api.matievisthekat.dev
          
      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './web/public/*'
          remote_path: '/var/www/matievisthekat.dev/web/public/'
